version: "3"
services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=test
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

